set_parameter:
  name: Set Parameter
  description: Set a configurable parameter for Adaptive Climate
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    parameter:
      name: Parameter
      description: Configuration parameter to set
      required: true
      selector:
        select:
          options:
            - value: "min_comfort_temp"
              label: "Minimum Comfort Temperature (18-30°C)"
            - value: "max_comfort_temp"
              label: "Maximum Comfort Temperature (18-30°C)"
            - value: "temperature_change_threshold"
              label: "Temperature Change Threshold (0.1-5.0°C)"
            - value: "override_temperature"
              label: "Override Temperature (-2.0 to 2.0°C)"
            - value: "comfort_category"
              label: "Comfort Category (I/II)"
            - value: "energy_save_mode"
              label: "Energy Save Mode (boolean)"
            - value: "auto_mode_enable"
              label: "Auto Mode Enable (boolean)"
    value:
      name: Value
      description: New value for the parameter
      required: true
      selector:
        text:

reset_parameter:
  name: Reset Parameter
  description: Reset a parameter to its default value
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    parameter:
      name: Parameter
      description: Configuration parameter to reset
      required: true
      selector:
        select:
          options:
            - value: "min_comfort_temp"
              label: "Minimum Comfort Temperature"
            - value: "max_comfort_temp"
              label: "Maximum Comfort Temperature"
            - value: "temperature_change_threshold"
              label: "Temperature Change Threshold"
            - value: "override_temperature"
              label: "Override Temperature"
            - value: "comfort_category"
              label: "Comfort Category"
            - value: "energy_save_mode"
              label: "Energy Save Mode"
            - value: "auto_mode_enable"
              label: "Auto Mode Enable"

set_comfort_category:
  name: Set Comfort Category
  description: Set ASHRAE 55 comfort category (I = ±2.5°C, II = ±3.5°C)
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    category:
      name: Comfort Category
      description: ASHRAE 55 comfort category
      required: true
      selector:
        select:
          options:
            - value: "I"
              label: "Category I (±2.5°C - Higher comfort)"
            - value: "II"
              label: "Category II (±3.5°C - Standard comfort)"

update_calculations:
  name: Update Calculations
  description: Force recalculation of comfort parameters and apply changes
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate

set_temporary_override:
  name: Set Temporary Override
  description: Set temporary temperature override for short duration
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    temperature:
      name: Temperature
      description: Target temperature for temporary override
      required: true
      selector:
        number:
          min: 10
          max: 40
          step: 0.5
          unit_of_measurement: "°C"
    duration_minutes:
      name: Duration (minutes)
      description: Override duration in minutes (0 = permanent until cleared)
      default: 30
      selector:
        number:
          min: 0
          max: 1440
          step: 5
          unit_of_measurement: "minutes"

redetect_capabilities:
  name: Re-detect Device Capabilities
  description: Force re-detection of device capabilities (cooling, heating, fan, dry modes)
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate



