set_parameter:
  name: Set Parameter
  description: Set a configurable parameter for Adaptive Climate
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    parameter:
      name: Parameter
      description: Configuration parameter to set
      required: true
      selector:
        select:
          options:
            - value: "min_comfort_temp"
              label: "Minimum Comfort Temperature (18-30°C)"
            - value: "max_comfort_temp"
              label: "Maximum Comfort Temperature (18-30°C)"
            - value: "temperature_change_threshold"
              label: "Temperature Change Threshold (0.1-5.0°C)"
            - value: "air_velocity"
              label: "Air Velocity (0.0-2.0 m/s)"
            - value: "setback_temperature_offset"
              label: "Setback Temperature Offset (0.0-10.0°C)"
            - value: "prolonged_absence_minutes"
              label: "Prolonged Absence Minutes (5-480)"
            - value: "auto_shutdown_minutes"
              label: "Auto Shutdown Minutes (10-1440)"
            - value: "comfort_temp_min_offset"
              label: "Comfort Min Offset (-5.0-0.0°C)"
            - value: "comfort_temp_max_offset"
              label: "Comfort Max Offset (0.0-5.0°C)"
            - value: "comfort_category"
              label: "Comfort Category (I/II/III)"
            - value: "comfort_precision_mode"
              label: "Comfort Precision Mode (boolean)"
            - value: "use_operative_temperature"
              label: "Use Operative Temperature (boolean)"
            - value: "adaptive_air_velocity"
              label: "Adaptive Air Velocity (boolean)"
            - value: "auto_shutdown_enable"
              label: "Auto Shutdown Enable (boolean)"
            - value: "energy_save_mode"
              label: "Energy Save Mode (boolean)"
            - value: "use_occupancy_features"
              label: "Use Occupancy Features (boolean)"
            - value: "humidity_comfort_enable"
              label: "Humidity Comfort Enable (boolean)"
    value:
      name: Value
      description: New value for the parameter
      required: true
      selector:
        text:

reset_parameter:
  name: Reset Parameter
  description: Reset a parameter to its default value
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    parameter:
      name: Parameter
      description: Configuration parameter to reset
      required: true
      selector:
        select:
          options:
            - value: "min_comfort_temp"
              label: "Minimum Comfort Temperature"
            - value: "max_comfort_temp"
              label: "Maximum Comfort Temperature"
            - value: "temperature_change_threshold"
              label: "Temperature Change Threshold"
            - value: "air_velocity"
              label: "Air Velocity"
            - value: "setback_temperature_offset"
              label: "Setback Temperature Offset"
            - value: "prolonged_absence_minutes"
              label: "Prolonged Absence Minutes"
            - value: "auto_shutdown_minutes"
              label: "Auto Shutdown Minutes"
            - value: "comfort_temp_min_offset"
              label: "Comfort Min Offset"
            - value: "comfort_temp_max_offset"
              label: "Comfort Max Offset"
            - value: "comfort_category"
              label: "Comfort Category"
            - value: "comfort_precision_mode"
              label: "Comfort Precision Mode"
            - value: "use_operative_temperature"
              label: "Use Operative Temperature"
            - value: "adaptive_air_velocity"
              label: "Adaptive Air Velocity"
            - value: "auto_shutdown_enable"
              label: "Auto Shutdown Enable"
            - value: "energy_save_mode"
              label: "Energy Save Mode"
            - value: "use_occupancy_features"
              label: "Use Occupancy Features"
            - value: "humidity_comfort_enable"
              label: "Humidity Comfort Enable"

set_manual_override:
  name: Set Manual Override
  description: Set manual temperature override with optional duration
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
    temperature:
      name: Temperature
      description: Target temperature for override
      required: true
      selector:
        number:
          min: 10
          max: 40
          step: 0.5
          unit_of_measurement: "°C"
    duration_hours:
      name: Duration (hours)
      description: Override duration in hours (0 = permanent until cleared)
      default: 1
      selector:
        number:
          min: 0
          max: 24
          step: 1
          unit_of_measurement: "hours"

clear_manual_override:
  name: Clear Manual Override
  description: Clear manual override and resume adaptive control
  fields:
    entity_id:
      name: Entity ID
      description: Adaptive Climate binary sensor entity ID
      required: true
      selector:
        entity:
          domain: binary_sensor
          integration: adaptive_climate
