name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: "integration"
